name: Test

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [14.x, 16.x, 17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install modules
        run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test --passWithNoTests
      - name: Run e2e tests
        run: yarn test:e2e

    services:
      rabbitmq:
        image: rabbitmq:3
        ports:
          - 5672:5672
